Add styling
Simpleshaikh1/Book-Store pull request #8
Opened 2023-06-30 14:26 UTC by Simpleshaikh1

I added styling to look like the design

2023-06-30 17:00 UTC, brainconnect93 requested changes
### Hi @Simpleshaikh1, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️
- Styling of the bookstore CMS project ✔️
- Zeplin Design template used for the design ✔️
- There is a good use of Git flow ✔️

### Changes Required

- [ ] I would kindly suggest you work on the MIT license link as currently the link is broken and throwing error 404

MIT License 👇 

![mit](https://github.com/Simpleshaikh1/Book-Store/assets/78634841/f66284e7-e7df-4b9c-970a-b436bbab1b47)


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 17:00 UTC, brainconnect93 commented on src/components/BookList.jsx
> +
- [ ] Great effort working on the styling of the bookstore project, But currently I could not see the books added and the form input to add the book I would kindly suggest you work on it and be sure the books rendered on the page in order to be able to see the design you have implemented.

Below is the video recording of my claim.

[screen-capture.webm](https://github.com/Simpleshaikh1/Book-Store/assets/78634841/2495942b-a520-490c-9303-c13d3cf2d586)

2023-07-01 08:16 UTC, Simpleshaikh1 commented on src/components/BookList.jsx
> +
Thank you sir.

2023-07-01 16:51 UTC, merged

2023-07-01 17:31 UTC, bobb-Rob reviewed
## STATUS: CHANGES REQUIRED ♻️

Hi @Simpleshaikh1, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 17:31 UTC, bobb-Rob commented on src/App.css
> +  border: 1px solid rgb(221, 229, 224);
- [ ] Well done on this project. But if you look closely at the Zeplin design, you will see a huge disparity with your project style implementation. See below the list of things you should fix 👇🏾 

    - Use the correct colors where necessary. inspect the Zeplin design to see,
    - Use the correct font family and font size as used in the Zeplin
    - Ensure unnecessary borders are removed from buttons.
    - The progress bar has a percentage figure beside it and it is not like you have done. compare them. You can use an npm package. 
    - The chapter text is missing 

You will more issues pointed out in the image below.

## Your design
![image](https://github.com/Simpleshaikh1/Book-Store/assets/84156714/90fee2c1-f971-4c0c-8b49-f3f94af1c773)

## Zeplin design
![image](https://github.com/Simpleshaikh1/Book-Store/assets/84156714/688bc8ba-f804-4a00-85d7-d28b0af9b968)

Please work on the styling some more. I have not touched all the issues but you should ensure your project resembles the Zeplin design as much as possible.